### Participants
GET http://localhost:3030/participants
###
GET http://localhost:3030/participants/:id
###
POST http://localhost:3030/participants
###
DELETE http://localhost:3030/participants/:id
###
PATCH http://localhost:3030/participants/:id


### Courses
GET http://localhost:3030/courses
###
GET http://localhost:3030/courses/:id
###
POST http://localhost:3030/courses
Accept: application/json
Content-Type: application/json

{
    "label": "Boostrap",
    "description": "Framework CSS",
    "volume": 120,
    "startDate": "2021-11-29"
}

###
DELETE http://localhost:3030/courses/:id
###
PATCH http://localhost:3030/courses/:id